# Hospital Data

This project explores and maps hospital-level data from various sources ([CMS](https://data.cms.gov) &
[HIFLD](https://hifld-geoplatform.hub.arcgis.com)), presented in a [Quarto](https://quarto.org) document.
It demonstrates the application of GIS techniques using Python libraries to analyze
and visualize data. Key methods include acquiring data from APIs, geocoding addresses into coordinates,
calculating geospatial distances, working with shapefiles to define geographic boundaries, merging datasets
with fuzzy matching to resolve address inconsistencies, and creating interactive maps with Folium.

## US Map
<iframe src="notebooks/outputs/us_heatmap.html" width="100%" height="600px"></iframe>


## Maryland Maps

<!-- Buttons positioned at the top for consistent navigation -->
<div class="button-container">
  <button onclick="showMap('heatmap')">Show Heatmap</button>
  <button onclick="showMap('choropleth')">Show Choropleth Map</button>
  <button onclick="showMap('dotmap')">Show Dot Map</button>
</div>


<div id="heatmap">
  <iframe src="notebooks/outputs/maryland_heatmap.html" width="100%" height="600px"></iframe>
</div>

<div id="choropleth" class="hidden">
  <iframe src="notebooks/outputs/maryland_choropleth.html" width="100%" height="600px"></iframe>
</div>


<div id="dotmap" class="hidden">
  <iframe src="notebooks/outputs/maryland_marker.html" width="100%" height="600px"></iframe>
</div>


<!-- Add the JavaScript to control map visibility -->
<script>
  function showMap(mapId) {
    // Hide all maps
    document.getElementById('heatmap').classList.add('hidden');
    document.getElementById('choropleth').classList.add('hidden');
    document.getElementById('dotmap').classList.add('hidden');

    // Show the selected map
    document.getElementById(mapId).classList.remove('hidden');
  }
</script>


## Baltimore Map
Hospitals within 15 miles of downtown Baltimore
<iframe src="notebooks/outputs/baltimore.html" width="100%" height="600px"></iframe>